steps:
  - label: "Install Dependencies"
    command: "npm install"

  - label: "Run Linter"
    command: 
      - "./bin/test.sh"
      - "node -v"

  - label: "Run Unit Tests"
    command: "npm run test"

  - label: "Build Production"
    command: "npm run build -- --prod"

  - block: "Deploy"
    prompt: "Deploy to production?"

  - label: "Deploy to Production"
    command: "deploy-scripts/deploy.sh"
